### ISSUE TITLE
Component emits escaped JavaScript code

### ISSUE THREAD

**Issue by hopsoft** [whitefusionhq/sl-tags-input#1]
I attempted to add this much needed component to a Rails project. Everything works well for the native Shoelace components, but the `sl-tags-input` emits the related escaped JavaScript in the development environment. _I haven't tried compiling assets and running under a production environment yet._ 

Note that I've added some Shoelace helpers to clean up some of the ERB templating as it relates to Shoelace components. I've tried `sl-tags-input` both with and without the helpers but get the same result.

It's very likely related to something I'm doing in the Rails project, but thought I'd bring it to your attention as I expect others may bump into something similar.

<img width="1439" alt="Timesheet 2021-04-04 08-59-59" src="https://user-images.githubusercontent.com/32920/113513390-bef5ae80-9526-11eb-83f9-ba0c7b163005.png">

**Comment by jaredcwhite** [comment]
Thanks for the heads up! That's very strange…it looks like a lit-html object itself somehow got rendered into the HTML without being parsed first. Hard to tell what's going on unless you have a test repo or CodePen or something I could try to reproduce with.

**Comment by jaredcwhite** [comment]
@hopsoft Any resolution to this? I'd be happy to investigate if I could get a repo example.

**Comment by hopsoft** [comment]
No. Unfortunately I haven't done any additional work on this as I opt'd to go for the lazy solution of a comma delimited value in a standard input.

**Comment by jaredcwhite** [comment]
Well, for some reason, it just started happening to me on a project. Very weird! Guess I'll try to investigate a bit more…

**Comment by jaredcwhite** [comment]
Updated to latest release of Lit 2, published 0.10.0, and then that worked again on my project. So potentially a mismatch between Lit versions could cause this weird rendering error. I'll consider this fixed for now, but happy to revisit if anyone else comes across it again.
