### ISSUE TITLE
JSON string of tag objects requires double quoted keys/values

### ISSUE THREAD

**Issue by hopsoft** [whitefusionhq/sl-tags-input#2]
It's possible to assign existing tags declaratively, but it requires a specific format for the JSON string. Namely, the quotes for keys/values must be double quotes otherwise the component will not render. Instead it produces the following error.

```
Uncaught (in promise) TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
```

This works 

```html
<sl-tags-input tags='[{"label": "Tag Here", "value": "tag-123"}]'>...</sl-tags-input>
```

...but, this with throw an error

```html
<sl-tags-input tags="[{'label': 'Tag Here', 'value': 'tag-123'}]">...</sl-tags-input>
```

Also, pre-populating tags declaratively via `sl-menu-item` doesn't work. It would be cool to switch to this mechanism -vs- the JSON string for declarative pre-pop.

**Comment by jaredcwhite** [comment]
@hopsoft Technically speaking it's not a bug that it can't render single-quoted keys/values since that's not valid JSON. But I do agree it'd be nice to have a more HTML-friendly way to declaratively populate tags.
